<?xml version="1.0" encoding="ISO-8859-1" ?>

<!--
  This database is being provided to you, the LICENSEE, by
  CL Research and Oxford University Press under the following license.
  By obtaining, using and/or copying this database, you agree that you have
  read, understood, and will comply with these terms and conditions.:

  Permission to use, copy, modify and distribute this
  database and its documentation for any purpose and without fee or
  royalty is hereby granted, provided that you agree to comply with
  the following copyright notice and statements, including the disclaimer,
  and that the same appear on ALL copies of the database and
  documentation, including modifications that you make for internal
  use or for distribution.

  The Preposition Project Copyright 2002-8 by CL Research and
  Oxford University Press.  All rights reserved.

  THIS DATABASE IS PROVIDED "AS IS" AND CL RESEARCH and OXFORD
  UNIVERSITY PRESS MAKE NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR
  IMPLIED.  BY WAY OF EXAMPLE, BUT NOT LIMITATION, CL RESEARCH AND
  OXFORD UNIVERSITY PRESS MAKE NO REPRESENTATIONS OR WARRANTIES OF MERCHANT-
  ABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE OR THAT THE USE
  OF THE LICENSED DATABASE OR DOCUMENTATION WILL NOT
  INFRINGE ANY THIRD PARTY PATENTS, COPYRIGHTS, TRADEMARKS OR
  OTHER RIGHTS.

  The name of CL Research or Oxford University Press may not be used in
  advertising or publicity pertaining to distribution of the software
  and/or database.  Title to copyright in this database and
  any associated documentation shall at all times remain with
  CL Research and Oxford University Press and LICENSEE agrees to preserve same.
-->

<!DOCTYPE tpp [
<!--

  DTD for The Preposition Project Database

-->

<!-- ***************** ROOT ELEMENT ***************** -->

<!ELEMENT  tpp  ( entry )*  >

<!-- ***************** ENTRY ELEMENTS ***************** -->

<!--  entry: entry of The Preposition Project Dictionary -->
<!ELEMENT  entry ( S )* >

<!--  S: entry section (containing lexical data)  -->
<!ELEMENT  S
                  ( #PCDATA |
                    hg |
                    un |
                    xg )*  >


<!-- ***************** OTHER ELEMENTS ***************** -->

<!--  aprop: attachment properties of the preposition sense  -->
<!ELEMENT  aprops
                  ( #PCDATA )*  >

<!--  b: bold face  -->
<!ELEMENT  b
                  ( #PCDATA |
                    exb )*  >

<!--  com: lexicographer comments in analyzing the preposition sense  -->
<!ELEMENT  com
                  ( #PCDATA )*  >

<!--  cprop: properties of the preposition object/complement  -->
<!ELEMENT  cprop
                  ( #PCDATA )*  >

<!--  df: definition text  -->
<!ELEMENT  df
                  ( #PCDATA |
                    i |
                    xg |
                    vg |
                    ge |
                    reg )*  >

<!--  eg: example sentence group  -->
<!ELEMENT  eg
                  ( #PCDATA |
                    ex |
                    gg |
                    fg |
                    reg |
                    ge )*  >

<!--  ex: example sentence, italic face  -->
<!ELEMENT  ex
                  ( #PCDATA |
                    exb |
                    r |
                    i )*  >

<!--  exb: emphasized word or phrase in example sentence, bold italic face  -->
<!ELEMENT  exb
                  ( #PCDATA |
                    r )*  >


<!--  f: form (syntactic construction)  -->
<!ELEMENT  f
                  ( #PCDATA |
                    vg |
                    i )*  >

<!--  fepreps: other prepositions used to express the
		same FrameNet frame element
-->
<!ELEMENT  fepreps
                  ( #PCDATA )*  >

<!--  fg: form group wrapper  -->
<!ELEMENT  fg
                  ( #PCDATA |
                    f |
                    ge |
                    reg |
                    sy )*  >

<!--  frfes: FrameNet frame elements identified
		in tagging instances of the preposition
-->
<!ELEMENT  frfes
                  ( #PCDATA )*  >

<!--  ge: geographical label (US, Brit, etc)  -->
<!ELEMENT  ge
                  ( #PCDATA |
                    r )*  >

<!--  gg: grammar group  -->
<!ELEMENT  gg
                  ( #PCDATA |
                    sy |
                    f )*  >

<!--  hg: headword group  -->
<!ELEMENT  hg
                  ( #PCDATA |
                    hw |
                    vg |
                    sj |
                    reg |
                    ge |
                    fg |
                    gg )*  >

<!--  hw: headword  -->
<!ELEMENT  hw
                  ( #PCDATA |
                    r )*  >

<!--  i: italic face  -->
<!ELEMENT  i
                  ( #PCDATA )*  >

<!--  l: lemma (phrase, phrasal verb, or derivative)  -->
<!ELEMENT  l
                  ( #PCDATA |
                    vg )*  >

<!--  morph: morphological unit (non-displaying)  -->
<!ELEMENT  morph
                  ( mu+ )   >

<!--  ms: meaning statement (subsidiary sense)  -->
<!ELEMENT  ms
                  ( #PCDATA |
                    nlp |
                    df |
                    ex |
                    gg |
                    reg |
                    fg |
                    sj |
                    ge |
                    eg |
                    vg |
                    xg )*  >

<!--  mu: unknown  -->
<!ELEMENT  mu
                  ( #PCDATA |
                    inf |
                    ph )*  >
<!ATTLIST  mu  sy  ( CDATA )  #REQUIRED  >
<!ATTLIST  mu  v  ( d | z | s | a | b )  #IMPLIED  >
<!ATTLIST  mu  gen  ( m | f )  #IMPLIED  >

<!--  opreps: other prepositions synonymic for this sense  -->
<!ELEMENT  opreps
                  ( #PCDATA )*  >

<!--  nlp: NLP data wrapper (non-displaying)  -->
<!ELEMENT  nlp
                  ( morph |
                    sup |
                    ss )*  >

<!--  p: paragraph (line break)  -->
<!ELEMENT  p
                  ( #PCDATA |
                    b |
                    ex |
                    xg |
                    i |
                    exb )*  >

<!--  ps: part of speech  -->
<!ELEMENT  ps
                  ( #PCDATA )   >

<!--  qpar: paragraphs where discussed in Quirk et al.  -->
<!ELEMENT  qpar
                  ( #PCDATA )*  >

<!--  qsyn: syntactic position of a preposition in this
		sense, using Quirk et al. categorization
-->
<!ELEMENT  qsyn
                  ( #PCDATA )*  >

<!--  r: roman (plain) face  -->
<!ELEMENT  r
                  ( #PCDATA )   >

<!--  reg: register label (slang, informal, etc)  -->
<!ELEMENT  reg
                  ( #PCDATA |
                    r )*  >

<!--  senseid: unique sense identifier for this sense  -->
<!ELEMENT  senseid
                  ( #PCDATA )*  >

<!--  sj: subject label (Physics, Cricket, etc)  -->
<!ELEMENT  sj
                  ( #PCDATA |
                    r )*  >

<!--  srel: relation of this sense to a core sense  -->
<!ELEMENT  srel
                  ( #PCDATA )*  >

<!--  srtype: semantic role type for this sense  -->
<!ELEMENT  srtype
                  ( #PCDATA )*  >

<!--  ss: special subject domain categorizer (non-displaying)  -->
<!ELEMENT  ss
                  ( #PCDATA )   >

<!--  sup: superordinate taxonomic categorizer (non-displaying)  -->
<!ELEMENT  sup
                  ( #PCDATA )   >

<!--  sy: syntactic category  -->
<!ELEMENT  sy
                  ( #PCDATA )   >

<!--  un: usage note  -->
<!ELEMENT  un
                  ( #PCDATA |
                    b |
                    ex |
                    xg |
                    p |
                    i )*  >

<!--  v: variant form (italic face)  -->
<!ELEMENT  v
                  ( #PCDATA |
                    i )*  >

<!--  vg: variant block wrapper  -->
<!ELEMENT  vg
                  ( #PCDATA |
                    v |
                    ge |
                    reg |
                    sj |
                    i |
                    sy )*  >

<!--  x: cross-reference target entry (small caps)  -->
<!ELEMENT  x
                  ( #PCDATA )*  >
<!ATTLIST  x  cn  ( ID )  #REQUIRED  >


<!--  xg: cross-reference group wrapper  -->
<!ELEMENT  xg
                  ( #PCDATA |
                    xu |
                    i |
                    reg )*  >

<!--  xl: cross-reference target italic lemma  -->
<!ELEMENT  xl
                  ( #PCDATA )*  >

<!--  xu: cross-reference to usage note  -->
<!ELEMENT  xu
                  ( #PCDATA )   >

<!-- ***************** ENTITIES ***************** -->

<!ENTITY agrave "&#224;" >
<!ENTITY egrave "&#232;" >
<!ENTITY ndash "&#150;" >
]>
<tpp>
  <entry>
    <S><hg><hw>a cut above</hw></hg></S>
    <S><l>a cut above</l> <reg>informal</reg> <df>noticeably superior to:</df> <ex>she's a cut above the rest.</ex><nlp><sup>Tandem</sup><senseid>1(1)</senseid><morph><mu sy="PHR" v="b">a cut above</mu></morph></nlp><srtype>ThingOutranked</srtype><qsyn>1 3a 3b</qsyn><qpar>*</qpar><opreps>over, on top of, above</opreps><cprop>noun, often an agent or person.</cprop><aprop>copula</aprop><srel>core: superiority</srel><com>same as "better than"; close enough to others sharing the type.</com></S>
  </entry>
  <entry>
    <S><hg><hw>&amp;agrave; la</hw></hg></S>
    <S>&amp;#149; <ps>preposition</ps> <df>(of a dish) cooked or prepared in a specified way:</df> <ex>fish cooked &amp;agrave; la meuni&amp;egrave;re.</ex><nlp><sup>Backdrop</sup><senseid>1(1)</senseid><ss>Cookery</ss><morph><mu sy="IN" v="b">&amp;agrave; la</mu></morph></nlp><srtype>Dish</srtype><qsyn>1 2a 3b</qsyn><qpar>*</qpar><cprop>a proper name; a culinary term</cprop><aprop>name of a prepared dish; adj or participle denoting food preparation</aprop><srel>(core)</srel></S>
    <S><ms><reg>informal</reg> <df>in the style or manner of:</df> <ex>afternoon talk shows &amp;agrave; la Oprah.</ex><nlp><sup>Membership</sup><senseid>2(1a)</senseid><morph><mu sy="IN" v="b">&amp;agrave; la</mu></morph></nlp></ms><srtype>Model</srtype><qsyn>1 3b</qsyn><qpar>*</qpar><opreps>(like)</opreps><cprop>a proper name</cprop><aprop>concrete or abstract noun; verb or participle denoting creation or execution</aprop><srel>3: generalizing extension to cover items other than food</srel></S>
  </entry>
  <entry>
    <S><hg><hw>abaft</hw> <sj>Nautical</sj></hg></S>
    <S>&amp;#149; <ps>preposition</ps> <df>nearer the stern than; behind.</df><nlp><sup>Spatial</sup><senseid>1(1)</senseid><ss>Nautical</ss><morph><mu sy="IN" v="b">abaft</mu></morph></nlp><srtype>ShipPart</srtype><qsyn>1 2a 3a</qsyn><qpar>*</qpar><opreps>behind</opreps><cprop>part of a ship</cprop><aprop>verbs of location; nouns denoting ship parts</aprop><srel>core: location</srel><com>Nautical use only; otherwise =1(1) of "behind."</com></S>
  </entry>
  <entry>
    <S><hg><hw>aboard</hw></hg></S>
    <S>&amp;#149; <ps>preposition</ps> <df>on or into (a ship, aircraft, train, or other vehicle):</df> <gg>as <sy>adv.</sy></gg> <ex>the plane crashed, killing all 158 people aboard</ex> &amp;#124; <eg><reg>figurative</reg> <ex>coming aboard as IBM's new chairman</ex></eg> &amp;#124; <eg><gg>as <sy>prep.</sy></gg> <ex>I climbed aboard the yacht.</ex></eg><nlp><sup>Spatial</sup><senseid>1(1)</senseid><morph><mu sy="RB" v="b">aboard</mu></morph><morph><mu sy="IN" v="b">aboard</mu></morph></nlp><srtype>Conveyance</srtype><qsyn>1 2a 3a</qsyn><qpar>9.15-16</qpar><opreps>in, on, onto</opreps><cprop>a conveyance, usu prec by determiner or possessive</cprop><aprop>verbs of motion, mounting, embarking.</aprop><srel>core: conveyance</srel><com>Same as on 16(7b)</com></S>
    <S><ms><df>on or on to (a horse):</df> <eg><gg>as <sy>adv.</sy></gg> <ex>with Richard Migliore aboard, he won the cup at a gallop.</ex></eg><nlp><sup>Spatial</sup><senseid>2(1a)</senseid><morph><mu sy="RB" v="b">aboard</mu></morph><morph><mu sy="IN" v="b">aboard</mu></morph></nlp></ms><srtype>Conveyance</srtype><qsyn>1 2a 3a</qsyn><qpar>9.15-16</qpar><opreps>in, on, onto</opreps><cprop>Analysis pending: a horse, usu prec by determiner or possessive</cprop><aprop>verbs of motion, mounting, embarking.</aprop><srel>2: specific to cases where the object is a horse</srel></S>
  </entry>
  <entry>
    <S><hg><hw>about</hw></hg></S>
    <S>&amp;#149; <ps>preposition</ps></S>
    <S><b>1</b>. <df>on the subject of; concerning:</df> <ex>I was thinking about you</ex> &amp;#124; <ex>a book about ancient Greece</ex> &amp;#124; <ex>it's <exb>all about</exb> having fun.</ex><nlp><sup>Topic</sup><senseid>1(1)</senseid><morph><mu sy="IN" v="b">about</mu></morph></nlp><srtype>ThingConsidered</srtype><qsyn>1 2a 3a</qsyn><qpar>9.57, 9.60</qpar><frfes>Awareness:Content; Awareness:Topic; Becoming_aware:Topic; Candidness:Topic; Certainty:Content; Certainty:Topic; Chatting:Topic; Cogitation:Topic; Coming_to_believe:Content; Coming_to_believe:Topic; Commitment:Topic; Communication_manner:Topic; Communication_noise:Topic; Communication_response:Topic; Contacting:Topic; Contrition:Action; Discussion:Topic; Emotion_active:Topic; Emotion_directed:Stimulus; Emotion_directed:Topic; Emotion_heat:Cause; Emotion_heat:Topic; Experiencer_subj:Content; Experiencer_subj:Topic; Expertise:Knowledge; Fairness_evaluation:Grounds; Hear:Topic; Hostile_encounter:Issue; Judgment:Reason; Judgment_communication:Evaluee; Judgment_communication:Reason; Judgment_direct_address:Reason; Judgment_direct_address:Topic; Memory:Topic; Mental_property:Practice; Partiality:Dispute; Quarreling:Issue; Questioning:Topic; Sociability:Content; Social_interaction_evaluation:Behavior; Social_interaction_evaluation:Topic; Speak_on_topic:Topic; Statement:Manner; Statement:Message; Statement:Topic; Strictness:Issue; Subject_stimulus:Stimulus; Telling:Message; Telling:Topic; Text:Topic; Volubility:Topic</frfes><opreps>on, over, of, with respect to</opreps><fepreps>of; to; as; at; such; in; on; against; toward; about; more; concerning; with; over; for; into; upon; regarding; my; one; sex; what; from; among; around; because; by; towards; after; through; not; under; an; due; either; something; japanese; that; his; answers; like; relating; the; pertaining; </fepreps><cprop>any NP; a subject of consideration</cprop><aprop>verbs and nouns of info processing, storage, or communication; adjs denoting feelings and attitudes</aprop><srel>core: subject</srel><com>Synonymous with over and on in many contexts, though not always interchangeable because of usage dictates.</com></S>
    <S><ms><df>so as to affect:</df> <ex>there's nothing we can do about it.</ex><nlp><sup>Topic</sup><senseid>2(1a)</senseid><morph><mu sy="IN" v="b">about</mu></morph></nlp></ms><srtype>ThingAffected</srtype><qsyn>2a 3a 3b</qsyn><qpar>9.57</qpar><frfes>Custom:Domain; Judgment:Evaluee; Judgment_communication:Topic; Prevarication:Topic</frfes><opreps>on, concerning, with respect to</opreps><fepreps>about; for; of; in; to; at; on; over; among; into; onto; with; towards; upon; against; as; </fepreps><cprop>any NP; sth affected by the POA</cprop><aprop>verbs of action and deliberation</aprop><srel>2: specific to cases where the subject of consideration is affected</srel><com>In the most general way, easily subsumed by the core sense.</com></S>
    <S><b>2</b>. <ge><r>chiefly</r> Brit.</ge> <df>used to indicate movement within a particular area:</df> <ex>she looked about the room.</ex><nlp><sup>Spatial</sup><senseid>3(2)</senseid><morph><mu sy="IN" v="b">about</mu></morph></nlp><srtype>PlaceSaturated</srtype><qsyn>2a 3a</qsyn><qpar>9.22</qpar><frfes>Carrying:Area; Cause_motion:Area; Cotheme:Area; Motion_noise:Area; Motion_noise:Path; Perception_active:Direction; Self_motion:Area</frfes><opreps>around, through</opreps><fepreps>about; all; around; behind; among; in; amongst; under; at; over; on; below; beneath; across; along; between; past; through; up; down; from; towards; back; after; to; alongside; inside; into; beyond; off; above; deep; northwards; westward; outside; toward; beside; somewhere; anywhere; close; a; throughout; near; upon; by; before; consistently; just; underneath; </fepreps><cprop>a space; sth capable of being navigated or inspected</cprop><aprop>verbs of motion and perception</aprop><srel>core: movement within an area</srel><com>ODE: chiefly Brit. Am choice for this is nearly always "around"</com></S>
    <S><ms><df>around</df></ms><nlp><sup>Spatial</sup><senseid>3(2)-1</senseid></nlp><srtype>PlaceSaturated</srtype><qsyn>2a 3a</qsyn><frfes>Body_movement:Goal; Cause_motion:Goal; Cause_to_move_in_place:Fixed_location; Dispersal:Goal_area; Hair_configuration:Location; Manipulation:Locus; Mass_motion:Area; Perception_active:Ground; Placing:Goal; Self_motion:Path</frfes><opreps>round (Brit), around</opreps><fepreps>against; to; out; over; into; on; behind; beneath; in; about; above; across; along; around; beside; at; before; by; up; onto; upon; towards; away; under; inside; outside; between; back; directly; down; firmly; closer; underneath; within; below; close; all; amongst; among; deeper; through; from; off; beyond; with; anywhere; deep; somewhere; the; aro; alongside; a; centrally; near; either; next; right; just; capacious; after; toward; past; for; due; forwards; further; straight; stinking; via; even; less; though; </fepreps><cprop>a focal point in space; a focus of attention (often personal pronoun); center of a circular area</cprop><aprop>verbs of motion and perception; other activities</aprop><srel>2: specific to cases where "round" or "around" also work</srel><com>See treatment.</com></S>
    <S><b>3</b>. <ge><r>chiefly</r> Brit.</ge> <df>used to express location in a particular place:</df> <ex>rugs were strewn about the hall</ex> &amp;#124; <ex>he produced a knife from somewhere about his person.</ex><nlp><sup>Spatial</sup><senseid>4(3)</senseid><morph><mu sy="IN" v="b">about</mu></morph></nlp><srtype>Place</srtype><qsyn>2a 3a</qsyn><qpar>9.22</qpar><frfes>Scrutiny:Ground</frfes><opreps>around, in, throughout</opreps><fepreps>for; of; on; from; in; into; within; back; beneath; between; beyond; about; among; around; through; under; at; over; up; </fepreps><cprop>a space, literal or abstract</cprop><aprop>verbs of location; objects that can be located in space</aprop><srel>2: specific to location without the idea of movement</srel><com>ODE: chiefly Brit. Am choice for this is nearly always "around"</com></S>
    <S><ms><df>used to describe a quality apparent in a person:</df> <ex>there was a look about her that said everything.</ex><nlp><sup>Possession</sup><senseid>5(3a)</senseid><morph><mu sy="IN" v="b">about</mu></morph></nlp></ms><srtype>OwnerOfAttribute</srtype><qsyn>1 3b</qsyn><qpar>9.57</qpar><frfes>Certainty:Cognizer; Judgment:Expressor; Mental_property:Behavior</frfes><opreps>concerning, with respect to</opreps><fepreps>about; of; over; by; on; in; to; against; upon; with; as; </fepreps><cprop>a person; a thing with attributes</cprop><aprop>an attributed quality</aprop><srel>1: attribute as a metaphor of location</srel><com>Could easily be a core sense, and closer in meaning to sense 1 than here. ODE falsely limits the comp to persons; I've expanded it, to include both "there was a look about her that said everything" and "there is something absurd about that marriage."</com></S>
  </entry>
  <entry>
    <S><hg><hw>above</hw></hg></S>
    <S>&amp;#149; <ps>preposition</ps></S>
    <S><b>1</b>. <df>in extended space over and not touching:</df> <ex>a display of fireworks above the town</ex> &amp;#124; <ex>a cable runs above the duct.</ex><nlp><sup>Spatial</sup><senseid>1(1)</senseid><morph><mu sy="IN" v="b">above</mu></morph></nlp><srtype>ThingSurmounted</srtype><qsyn>1 2a 3b</qsyn><qpar>9.19</qpar><frfes>Fluidic_motion:Area; Motion_directional:Area</frfes><opreps>over, on top of</opreps><fepreps>above; around; in; inside; beside; on; behind; at; over; </fepreps><cprop>a physical entity that can have sth above it</cprop><aprop>wide range of POSs. No pattern</aprop><srel>core: upwards from</srel><com>more or less identical to over 1(1)</com></S>
    <S><ms><df>extending upwards over:</df> <ex>she held her arms above her head.</ex><nlp><sup>Spatial</sup><senseid>2(1a)</senseid><morph><mu sy="IN" v="b">above</mu></morph></nlp></ms><srtype>ThingSurmounted</srtype><qsyn>1 2a 3a 3b</qsyn><qpar>9.19</qpar><frfes>Attaching:Goal; Body_movement:Goal; Change_posture:Goal; Path_shape:Area</frfes><opreps>over, on top of</opreps><fepreps>onto; in; into; on; for; round; over; around; above; across; directly; through; under; about; at; by; all; between; near; from; against; behind; beneath; along; beside; before; up; upon; towards; away; close; with; next; alongside; off; opposite; somewhere; amongst; among; </fepreps><cprop>a physical entity that can have sth above it</cprop><aprop>wide range of POSs. No pattern</aprop><srel>2: specific to extensions upwards from</srel><com>Not really different from 1(1)</com></S>
    <S><ms><df>higher than and to one side of; overlooking:</df> <ex>in the hills above the capital</ex> &amp;#124; <ex>on the wall above the altar.</ex><nlp><sup>Spatial</sup><senseid>3(1b)</senseid><morph><mu sy="IN" v="b">above</mu></morph></nlp></ms><srtype>ThingSurveyed</srtype><qsyn>1 2a 3b</qsyn><qpar>9.19, 9.26</qpar><opreps>over</opreps><cprop>a physical entity lower in space than the POA</cprop><aprop>a physical entity higher in space than the comp.</aprop><srel>2: specific to bi-level scenarios</srel><com>corresponds to over 3(1b). This sense is often implicit in the core sense, and also in sense 4(2).</com></S>
    <S><b>2</b>. <df>at a higher level or layer than:</df> <ex>from his flat above the corner shop</ex> &amp;#124; <ex>bruises above both eyes.</ex><nlp><sup>Spatial</sup><senseid>4(2)</senseid><morph><mu sy="IN" v="b">above</mu></morph></nlp><srtype>ThingSurmounted</srtype><qsyn>1 2a 3a 3b</qsyn><qpar>9.19</qpar><frfes>Becoming_aware:Ground; Biological_area:Relative_location; Body_movement:Path; Cause_motion:Path; Location_of_light:Ground; Make_Noise:Place; Natural_features:Relative_location; Path_shape:Goal; Perception_active:Direction; Perception_experience:Direction; Placing:Goal; Posture:Location; Residence:Location; Roadways:Area; Self_motion:Area; Self_motion:Path</frfes><opreps>over, on top of</opreps><fepreps>at; from; in; through; under; near; on; by; down; inside; about; above; to; among; round; along; between; of; beside; around; behind; beneath; across; over; into; right; towards; back; up; past; against; toward; after; beyond; straight; inlaid; within; ahead; below; amongst; his; outside; off; next; underneath; high; just; throughout; close; for; onto; halfway; deep; northwards; westward; well; with; anywhere; somewhere; the; aro; alongside; a; before; centrally; directly; upon; either; away; all; capacious; there; an; only; opposite; athwart; amidst; fairly; adjacent; upstream; shrewsbury; consistently; due; forwards; further; stinking; via; even; less; though; </fepreps><cprop>a physical entity that can have sth above it</cprop><aprop>wide range of POSs. No pattern</aprop><srel>core: over in space</srel><com>corresponds to over 1(1) and 4(2); little to choose between this and 2(1a)</com></S>
    <S><ms><df>higher in grade or rank than:</df> <ex>at a level above the common people.</ex><nlp><sup>Tandem</sup><senseid>5(2a)</senseid><morph><mu sy="IN" v="b">above</mu></morph></nlp></ms><srtype>ThingOutranked</srtype><qsyn>1 2a 3a 3b</qsyn><qpar>*</qpar><opreps>over, on top of</opreps><cprop>noun, often an agent or person.</cprop><aprop>copula</aprop><srel>2: specific to hierarchical relationships</srel><com>identical to over 5(2a)</com></S>
    <S><ms><df>considered of higher status or worth than; too good for:</df> <ex>she <exb>married above her</exb>.</ex><nlp><sup>Tandem</sup><senseid>6(2b)</senseid><morph><mu sy="IN" v="b">above</mu></morph></nlp></ms><srtype>EntitySubordinate</srtype><qsyn>1 2a 3a 3b</qsyn><qpar>*</qpar><cprop>often gerund; otherwise personal or reflexive pronoun.</cprop><aprop>copula</aprop><srel>3: extension to notion or superiority</srel><com>This is a sense not shared by "over"</com></S>
    <S><ms><df>in preference to:</df> <ex>the firm cynically chose profit above car safety.</ex><nlp><sup>Tandem</sup><senseid>7(2c)</senseid><morph><mu sy="IN" v="b">above</mu></morph></nlp></ms><srtype>ThingNotPreferred</srtype><qsyn>3a 3b</qsyn><qpar>*</qpar><frfes>Experiencer_subj:Degree; Judgment:Degree</frfes><opreps>instead of, in place of, over</opreps><fepreps>in; like; to; above; as; with; out; beyond; </fepreps><cprop>the rejected of two things</cprop><aprop>the preferred of two things</aprop><srel>2: specific to preference as a metaphor of relative location</srel><com>identical to over 7(2c)</com></S>
    <S><ms><df>at a higher volume or pitch than:</df> <ex>he seldom spoke above a whisper</ex> &amp;#124; <ex>the doorbell went unheard above the din.</ex><nlp><sup>Backdrop</sup><senseid>8(2d)</senseid><morph><mu sy="IN" v="b">above</mu></morph></nlp></ms><srtype>DrownedSound</srtype><qsyn>2a 3b</qsyn><qpar>*</qpar><frfes>Perception_experience:Ground</frfes><opreps>over</opreps><fepreps>20; in; on; inside; above; around; behind; below; beneath; from; just; outside; over; through; among; between; beyond; under; </fepreps><cprop>the quieter of two noises or sounds</cprop><aprop>nouns and verbs denoting sound or aural perception</aprop><srel>2: specific to competiting sounds</srel><com>Identical to over 9(2e)</com></S>
    <S><b>3</b>. <df>higher than (a specified amount, rate, or norm):</df> <ex>the food was well above average</ex> &amp;#124; <ex>above sea level.</ex><nlp><sup>Scalar</sup><senseid>9(3)</senseid><morph><mu sy="IN" v="b">above</mu></morph></nlp><srtype>Norm</srtype><qsyn>1 2a 3a</qsyn><qpar>*</qpar><frfes>Cause_motion:Goal; Cause_temperature_change:Temperature_goal; Change_position_on_a_scale:Value_2</frfes><opreps>over</opreps><fepreps>into; on; onto; at; in; over; inside; outside; towards; about; against; around; between; under; back; directly; across; down; firmly; above; behind; beneath; closer; underneath; within; before; below; close; up; all; amongst; among; deeper; upon; almost; by; </fepreps><cprop>an established norm</cprop><aprop>an entity for which norms exist; verbs of location on a scale.</aprop><srel>core: relationship to norm</srel><com>not really different from over 10(3), even though that sense doesn't mention idea of norms.</com></S>
  </entry>
  <entry>
    <S><hg><hw>absent</hw></hg></S>
    <S>&amp;#149; <ps>preposition</ps> <reg>formal,</reg> <ge>N. Amer.</ge> <df>without:</df> <ex>absent a willingness to negotiate, you can't have collective bargaining.</ex><nlp><sup>Void</sup><senseid>1(1)</senseid><morph><mu sy="IN" v="b">absent</mu></morph></nlp><srtype>ThingMissing</srtype><qsyn>1 2a</qsyn><qpar>9.55</qpar><opreps>without, minus</opreps><cprop>a thing missing or not present; of an abstraction</cprop><aprop>no pattern</aprop><srel>core: thing missing</srel><com>Same as 1(1) of "without"; formal</com></S>
  </entry>
  <entry>
    <S><hg><hw>according to</hw></hg></S>
    <S><b>1</b>. <df>as stated by or in:</df> <ex>the outlook for investors is not bright, according to financial experts.</ex><nlp><sup>Agent</sup><senseid>1(1)</senseid><morph><mu sy="PHR" v="b">according to</mu></morph></nlp><srtype>Authority</srtype><qsyn>1 2a 2b</qsyn><qpar>9.57, 9.63</qpar><cprop>person or document regarded as authoritative</cprop><aprop>reporting verbs; often a disjunct at beginning of sentence, or otherwise set off by commas</aprop><srel>core: reference authority</srel></S>
    <S><ms><df>in a manner corresponding or conforming to:</df> <ex>cook the rice according to the instructions.</ex><nlp><sup>MeansMedium</sup><senseid>2(1a)</senseid><morph><mu sy="PHR" v="b">according to</mu></morph></nlp></ms><srtype>MediumOfInstruction</srtype><qsyn>2a</qsyn><opreps>by</opreps><cprop>noun denoting an algorithm, plan, set of instructions</cprop><aprop>verbs denoting activity or process</aprop><srel>2: specific to purposeful activity</srel></S>
    <S><ms><df>in proportion to; in relation to</df> <ex>salary will be fixed according to experience.</ex><nlp><sup>Scalar</sup><senseid>3(1b)</senseid><morph><mu sy="PHR" v="b">according to</mu></morph></nlp></ms><srtype>ScaleOfReference</srtype><qsyn>2a 3a</qsyn><qpar>9.57</qpar><opreps>in proportion to, in relation to, in reference to, depending on</opreps><cprop>sth providing the base for a judgment; a scale</cprop><aprop>verbs of judgment, fixing, determination</aprop><srel>2: specific to judgments made accd to a reference</srel></S>
  </entry>
  <entry>
    <S><hg><hw>across</hw></hg></S>
    <S>&amp;#149; <ps>preposition</ps> &amp;#038; <ps>adverb</ps></S>